### ISSUE TITLE
add state_class attribute to sensors

### ISSUE THREAD

**Issue by csanner** [djtimca/hagooglewifi#83]
I cannot graph the download/upload speeds over time because the sensors do not have the state_class attribute.
https://developers.home-assistant.io/docs/core/entity/sensor/

I'll attempt to make the changes myself but comparing two different implementations of sensors I am having trouble finding similarites :)
I see I'll have a lot to learn

**Comment by rockwig** [comment]
Is there any work around for this? It would be nice to create charts with the data.

**Comment by thomasermesjo** [comment]
Yes. Create a new sensor based on the Download Speed sensor from this package.
Something like:
```
- sensor:
    - name: "Internet download speed"
      state_class: measurement
      device_class: data_rate
      state: >-
        {{ states('sensor.google_wifi_system_....._download_speed') }}
```
